// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/uber/crumb/internal/model/crumb_model.proto
package com.uber.crumb.internal.model

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.missingRequiredFields
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.Map
import kotlin.jvm.JvmField
import okio.ByteString

class CrumbMetadata(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED
  )
  val extensionKey: String,
  @field:WireField(
    tag = 2,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val producerMetadata: Map<String, String>,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CrumbMetadata, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing {
    throw AssertionError()
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CrumbMetadata) return false
    return unknownFields == other.unknownFields
        && extensionKey == other.extensionKey
        && producerMetadata == other.producerMetadata
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = extensionKey.hashCode()
      result = result * 37 + producerMetadata.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """extensionKey=$extensionKey"""
    if (producerMetadata.isNotEmpty()) result += """producerMetadata=$producerMetadata"""
    return result.joinToString(prefix = "CrumbMetadata{", separator = ", ", postfix = "}")
  }

  fun copy(
    extensionKey: String = this.extensionKey,
    producerMetadata: Map<String, String> = this.producerMetadata,
    unknownFields: ByteString = this.unknownFields
  ): CrumbMetadata = CrumbMetadata(extensionKey, producerMetadata, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CrumbMetadata> = object : ProtoAdapter<CrumbMetadata>(
      FieldEncoding.LENGTH_DELIMITED, 
      CrumbMetadata::class
    ) {
      private val producerMetadataAdapter: ProtoAdapter<Map<String, String>> =
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING)

      override fun encodedSize(value: CrumbMetadata): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.extensionKey) +
        producerMetadataAdapter.encodedSizeWithTag(2, value.producerMetadata) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CrumbMetadata) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.extensionKey)
        producerMetadataAdapter.encodeWithTag(writer, 2, value.producerMetadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CrumbMetadata {
        var extensionKey: String? = null
        val producerMetadata = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> extensionKey = ProtoAdapter.STRING.decode(reader)
            2 -> producerMetadata.putAll(producerMetadataAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return CrumbMetadata(
          extensionKey = extensionKey ?: throw missingRequiredFields(extensionKey, "extensionKey"),
          producerMetadata = producerMetadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CrumbMetadata): CrumbMetadata = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
